/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Friend_send_model;
import model.Other_user_model;

/**
 *
 * @author Huy1721
 */
public class Infomation_view extends javax.swing.JDialog {

    /**
     * Creates new form Infomation_view
     */
    Other_user_model otherUser;
    int Signall;
    Messenger_view ms;

    ListFriend_view lf;

    public Infomation_view(java.awt.Frame parent, boolean modal, Other_user_model user, int signal, Messenger_view jpanel) {
        super(parent, modal);
        initComponents();
        this.Signall = signal;
        this.otherUser = user;
        this.ms = jpanel;
        showView();
    }

    public Infomation_view(java.awt.Frame parent, boolean modal, Other_user_model user, int signal, ListFriend_view jpanel) {
        super(parent, modal);
        initComponents();
        this.Signall = signal;
        this.otherUser = user;
        this.lf = jpanel;
        showView();
    }

    public Infomation_view(java.awt.Frame parent, boolean modal, Other_user_model user, int signal) {
        super(parent, modal);
        initComponents();
        this.Signall = signal;
        this.otherUser = user;
        showView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_Info_Background = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txt_Info_Ten = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        input_Info_Fullname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        input_Info_Gender = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        input_Info_Birthday = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txt_Info_Avatar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Thông tin tài khoản");

        txt_Info_Ten.setText("jLabel3");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Thông tin cá nhân");

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Họ và tên");

        input_Info_Fullname.setEditable(false);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Giới tính");

        input_Info_Gender.setEditable(false);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("Ngày sinh");

        input_Info_Birthday.setEditable(false);

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Chỉnh sửa thông tin cá nhân");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(input_Info_Birthday, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(input_Info_Gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(input_Info_Fullname))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(txt_Info_Ten)
                .addGap(0, 142, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_Info_Ten)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(input_Info_Fullname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(input_Info_Gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(input_Info_Birthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
        );

        txt_Info_Avatar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txt_Info_Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(txt_Info_Avatar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_Info_Background, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_Info_Avatar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String signal = jButton1.getText();
        if (signal.equals("Chỉnh sửa thông tin cá nhân")) {// chỉnh sửa thông tin dành cho setting
            this.setVisible(false);
            Infomation_edit_view dtMau = new Infomation_edit_view(this.otherUser);
            dtMau.setLocationRelativeTo(null);
            dtMau.setVisible(true);
        } else if (signal.equals("Xóa lời mời")) {// xóa lời mời kết bạn đó, dành cho Friend send
            this.lf.Delete1();
        } else if (signal.equals("")) {
            JOptionPane.showMessageDialog(null, "Thử lại sau");
        } else { // ket ban với lời mời kết bạn đó, dành cho Friend accept
            this.lf.Delete2();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField input_Info_Birthday;
    private javax.swing.JTextField input_Info_Fullname;
    private javax.swing.JTextField input_Info_Gender;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel txt_Info_Avatar;
    private javax.swing.JLabel txt_Info_Background;
    private javax.swing.JLabel txt_Info_Ten;
    // End of variables declaration//GEN-END:variables

    private void showView() {
        // Load ảnh BackGround
        ImageIcon imageBackGround = new ImageIcon(
                getClass().getResource("/image_user_background/" + this.otherUser.getImage_back_ground()));
        Image img = imageBackGround.getImage();
        img = img.getScaledInstance(txt_Info_Background.getWidth(), txt_Info_Background.getHeight(), Image.SCALE_SMOOTH);

        imageBackGround = new ImageIcon(img);
        txt_Info_Background.setIcon(imageBackGround);

        // Load ảnh avatar
        ImageIcon imageAvatar = new ImageIcon(
                getClass().getResource("/image_user_avatar/" + this.otherUser.getImage_avatar()));
        Image img1 = imageAvatar.getImage();
        img = img1.getScaledInstance(txt_Info_Avatar.getWidth(), txt_Info_Avatar.getHeight(), Image.SCALE_SMOOTH);
        imageAvatar = new ImageIcon(img);
        txt_Info_Avatar.setIcon(imageAvatar);

        txt_Info_Ten.setText(this.otherUser.getUsername_other_user());
        input_Info_Fullname.setText(this.otherUser.getHo_ten());
        input_Info_Gender.setText(this.otherUser.getGender());
        input_Info_Birthday.setText(this.otherUser.getBirth_day());
        if (Signall == 0) {

        } else if (Signall == 1) {
            jButton1.setText("Kết bạn.");
        } else if (Signall == 2) {
            jButton1.setText("");
        } else if (Signall == 3) {
            jButton1.setText("Xóa lời mời");
        } else {
            jButton1.setText("Chỉnh sửa thông tin cá nhân");
        }
    }
}
