/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.Chat_controller;
import controller.Friend_accept_controller;
import controller.Friend_send_controller;
import controller.Group_controller;
import controller.Group_list_controller;
import controller.List_friend_controller;
import controller.Other_user_controller;
import controller.User_controller;
import java.awt.Component;
import java.awt.Image;
import java.awt.PopupMenu;
import java.awt.event.MouseEvent;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Objects;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import jdbc.Data_User;
import jdbc.InsertMSSQL;
import model.Chat_model;
import model.Friend_accept_model;
import model.Friend_send_model;
import model.Group_chat_model;
import model.Group_list_model;
import model.Group_model;
import model.List_friend_model;
import model.MessViewTemp;
import model.Other_user_model;

/**
 *
 * @author Huy1721
 */
public class ListFriend_view extends javax.swing.JPanel {

    /**
     * Creates new form Messenger_View
     */
    Messenger_view messenger_view;
    ListFriend_view listFriend_view;
    ToDoList_view toDoList_view;
    Data_User data_user;
    InsertMSSQL insertmssql;

    // tạo biến DAO để thực hiện Create_Delete_Update
    List_friend_controller list_friend_controller;
    User_controller user_controller;
    Friend_send_controller friend_send_controller;
    Friend_accept_controller friend_accept_controller;
    Other_user_controller other_user_controller;
    Chat_controller chat_controller;

    // tạo mảng để hứng biến mảng ArrayList
    ArrayList<ArrayList> dsObject; // mảng động 2 chiều chứa 5 nguồn 5 data, bao gồm G, GC, GL, LF, C;
    ArrayList<Group_model> ds_Group;
    ArrayList<Chat_model> ds_Chat;
    ArrayList<Group_list_model> ds_Group_list;
    ArrayList<List_friend_model> ds_List_friend;
    ArrayList<Group_chat_model> ds_Group_chat;
    ArrayList<Friend_accept_model> ds_Friend_accept;
    ArrayList<Friend_send_model> ds_Friend_send;
    ArrayList<Other_user_model> ds_Other_user;

    String loginname;

    public ListFriend_view(String Who_login) {
        loginname = Who_login;
        initComponents();
        FillToTable();
        ShowDown();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Popup_Accept = new javax.swing.JPopupMenu();
        Accept = new javax.swing.JMenuItem();
        Delete = new javax.swing.JMenuItem();
        ShowInfo = new javax.swing.JMenuItem();
        Popup_Send = new javax.swing.JPopupMenu();
        Delete1 = new javax.swing.JMenuItem();
        ShowInfo1 = new javax.swing.JMenuItem();
        Popup_Properties_Friend = new javax.swing.JPopupMenu();
        Friend_Delete2 = new javax.swing.JMenuItem();
        Friend_ShowInfo2 = new javax.swing.JMenuItem();
        popup_Group = new javax.swing.JPopupMenu();
        showInfomation = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_friend_dskb = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tab_friend = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tab_group = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        txt_friend_title = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tab_friend_ds = new javax.swing.JTable();

        Accept.setText("jMenuItem1");
        Accept.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AcceptMouseClicked(evt);
            }
        });
        Accept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcceptActionPerformed(evt);
            }
        });
        Popup_Accept.add(Accept);

        Delete.setText("jMenuItem2");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        Popup_Accept.add(Delete);

        ShowInfo.setText("jMenuItem3");
        ShowInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowInfoActionPerformed(evt);
            }
        });
        Popup_Accept.add(ShowInfo);

        Delete1.setText("jMenuItem2");
        Delete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete1ActionPerformed(evt);
            }
        });
        Popup_Send.add(Delete1);

        ShowInfo1.setText("jMenuItem3");
        ShowInfo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowInfo1ActionPerformed(evt);
            }
        });
        Popup_Send.add(ShowInfo1);

        Friend_Delete2.setText("jMenuItem2");
        Friend_Delete2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Friend_Delete2ActionPerformed(evt);
            }
        });
        Popup_Properties_Friend.add(Friend_Delete2);

        Friend_ShowInfo2.setText("jMenuItem3");
        Friend_ShowInfo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Friend_ShowInfo2ActionPerformed(evt);
            }
        });
        Popup_Properties_Friend.add(Friend_ShowInfo2);

        showInfomation.setText("jMenuItem1");
        showInfomation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showInfomationActionPerformed(evt);
            }
        });
        popup_Group.add(showInfomation);

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(153, 204, 255));
        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/user-icon.png"))); // NOI18N

        txt_friend_dskb.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        txt_friend_dskb.setForeground(new java.awt.Color(51, 51, 255));
        txt_friend_dskb.setText("Danh sách chờ kết bạn");
        txt_friend_dskb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_friend_dskbMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txt_friend_dskb)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(txt_friend_dskb)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(153, 204, 255));
        jPanel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/users-3-icon.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 255));
        jLabel5.setText("Danh sách gửi kết bạn");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Danh sách bạn bè & nhóm");

        tab_friend.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tab_friend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_friendMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tab_friendMouseReleased(evt);
            }
        });
        jScrollPane5.setViewportView(tab_friend);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("bạn bè", jPanel10);

        tab_group.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tab_group.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_groupMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tab_group);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("nhóm", jPanel11);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        txt_friend_title.setText("Danh sách chờ chấp nhận kết bạn từ bạn");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(txt_friend_title, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_friend_title, javax.swing.GroupLayout.PREFERRED_SIZE, 20, Short.MAX_VALUE)
                .addContainerGap())
        );

        tab_friend_ds.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tab_friend_ds.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tab_friend_dsMouseReleased(evt);
            }
        });
        jScrollPane6.setViewportView(tab_friend_ds);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tab_friend_dsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_friend_dsMouseReleased
        if (evt.getButton() == MouseEvent.BUTTON3) {
            if (evt.isPopupTrigger() && luaChonTab == 0) {
                Accept.setText("Chấp nhận kết bạn");
                Delete.setText("Xóa bạn người dùng này");
                ShowInfo.setText("Xem trang cá nhân");
                Popup_Accept.show(evt.getComponent(), evt.getX(), evt.getY());
            } else if (evt.isPopupTrigger() && luaChonTab == 3) {
                showInfomation.setText("Xem thông tin cá nhân người này");
                popup_Group.show(evt.getComponent(), evt.getX(), evt.getY());
            } else {
                Delete1.setText("Xóa lời mời kết bạn này");
                ShowInfo1.setText("Xem trang cá nhân");
                Popup_Send.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_tab_friend_dsMouseReleased

    private void AcceptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AcceptMouseClicked

    }//GEN-LAST:event_AcceptMouseClicked

    private void AcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptActionPerformed
        Accept();
    }//GEN-LAST:event_AcceptActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        luaChonTab = 1;
        ShowDown();
        txt_friend_title.setText("Danh sách gửi lời kết bạn");
    }//GEN-LAST:event_jLabel5MouseClicked

    private void txt_friend_dskbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_friend_dskbMouseClicked
        luaChonTab = 0;
        ShowDown();
        txt_friend_title.setText("Danh sách chờ chấp nhận kết bạn từ bạn");
    }//GEN-LAST:event_txt_friend_dskbMouseClicked

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        Delete2(); // Day la ham xoa loi ket ban ben friend accept
    }//GEN-LAST:event_DeleteActionPerformed

    public void Delete2() { // Day la ham xoa loi ket ban ben friend accept
        luachon = tab_friend_ds.getSelectedRow();
        Who_give_u = (String) tab_friend_ds.getValueAt(luachon, 1);
        int v = JOptionPane.showConfirmDialog(null, "Bạn chắc chắn muốn xóa lời mời kết bạn từ" + Who_give_u + "chứ?");
        if (v == JOptionPane.YES_OPTION) {
            Delete();
        } else {
            JOptionPane.showMessageDialog(null, "Đã hủy thao tác.");
        }
    }

    private void ShowInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowInfoActionPerformed
        ShowInfo();
    }//GEN-LAST:event_ShowInfoActionPerformed

    private void tab_friendMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_friendMouseReleased
        if (evt.getButton() == MouseEvent.BUTTON3) {
            if (evt.isPopupTrigger()) {
                Friend_Delete2.setText("Xóa kết bạn");
                Friend_ShowInfo2.setText("Xem trang cá nhân");
                Popup_Properties_Friend.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_tab_friendMouseReleased

    private void Friend_Delete2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Friend_Delete2ActionPerformed
        String Who_want_delete = (String) tab_friend.getValueAt(luachon2, 1);
        int v = JOptionPane.showConfirmDialog(null, "Bạn chắc chắn muốn xóa bạn bè với " + Who_want_delete + " chứ?");
        if (v == JOptionPane.YES_OPTION) {
            Delete_friend_Accept();
        } else {
            JOptionPane.showMessageDialog(null, "Đã hủy thao tác.");
        }
    }//GEN-LAST:event_Friend_Delete2ActionPerformed

    private void Friend_ShowInfo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Friend_ShowInfo2ActionPerformed
        ShowInfo2();
    }//GEN-LAST:event_Friend_ShowInfo2ActionPerformed
    int luachon2 = 0;
    private void tab_friendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_friendMouseClicked
        luachon2 = tab_friend.getSelectedRow();
    }//GEN-LAST:event_tab_friendMouseClicked

    private void Delete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete1ActionPerformed
        Delete1(); // Day la ham xoa loi ket ban ben friend send
    }//GEN-LAST:event_Delete1ActionPerformed

    public void Delete1() { // Day la ham xoa loi ket ban ben friend send
        luachon = tab_friend_ds.getSelectedRow();
        Who_give_u = (String) tab_friend_ds.getValueAt(luachon, 1);
        int v = JOptionPane.showConfirmDialog(null, "Bạn chắc chắn muốn xóa lời mời kết bạn gửi đến " + Who_give_u + " chứ?");
        if (v == JOptionPane.YES_OPTION) {
            Delete_friend();
        } else {
            JOptionPane.showMessageDialog(null, "Đã hủy thao tác.");
        }
    }

    private void ShowInfo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowInfo1ActionPerformed
        ShowInfo();
    }//GEN-LAST:event_ShowInfo1ActionPerformed

    int group_ID;

    private void tab_groupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_groupMouseClicked
        try {
            luaChonTab = 3;

            dtm = (DefaultTableModel) tab_friend_ds.getModel();
            dtm.setRowCount(0);

            luachon3 = tab_group.getSelectedRow();

            String TenNhom = (String) tab_group.getValueAt(luachon3, 1);

            String sql = "SELECT * FROM [Group] WHERE Name_group = ?";
            ArrayList dsProp = new ArrayList();
            dsProp.add(TenNhom);

            txt_friend_title.setText("Danh sách thành viên nhóm " + TenNhom);

            ResultSet rs = jdbc.Helper_JDBC.query(sql, dsProp);

            if (rs.next()) {
                group_ID = rs.getInt(1);
            }

            int count = 0;

            for (Group_list_model item : dsGroup_list_paticipant) {
                if (group_ID == item.getID_group()) {
                    Other_user_model dtMau = other_user_controller.Select(item.getUsername_other_user());
                    dtm.addRow(new Object[]{dtMau.getImage_avatar(), dtMau.getUsername_other_user(), dtMau.getHo_ten()});
                    count++;
                }
            }

            if (count < dsGroup_list_paticipant.size() - 1) {
                Other_user_model dtMau = other_user_controller.Select(loginname);
                dtm.addRow(new Object[]{dtMau.getImage_avatar(), dtMau.getUsername_other_user(), dtMau.getHo_ten()});
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tab_groupMouseClicked

    private void showInfomationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showInfomationActionPerformed
        luachon3 = tab_friend_ds.getSelectedRow();
        Who_give_u = (String) tab_friend_ds.getValueAt(luachon3, 1);
        Other_user_model dtMau = other_user_controller.Select(Who_give_u);
        Infomation_view dt = new Infomation_view(null, true, dtMau, 2, this);
        dt.setLocationRelativeTo(null);
        dt.setVisible(true);

    }//GEN-LAST:event_showInfomationActionPerformed

    int luachon3 = 0;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Accept;
    private javax.swing.JMenuItem Delete;
    private javax.swing.JMenuItem Delete1;
    private javax.swing.JMenuItem Friend_Delete2;
    private javax.swing.JMenuItem Friend_ShowInfo2;
    private javax.swing.JPopupMenu Popup_Accept;
    private javax.swing.JPopupMenu Popup_Properties_Friend;
    private javax.swing.JPopupMenu Popup_Send;
    private javax.swing.JMenuItem ShowInfo;
    private javax.swing.JMenuItem ShowInfo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPopupMenu popup_Group;
    private javax.swing.JMenuItem showInfomation;
    private javax.swing.JTable tab_friend;
    private javax.swing.JTable tab_friend_ds;
    private javax.swing.JTable tab_group;
    private javax.swing.JLabel txt_friend_dskb;
    private javax.swing.JLabel txt_friend_title;
    // End of variables declaration//GEN-END:variables

    DefaultTableModel dtm;

    private void FillToTable() {
        try {

            tab_friend.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            tab_friend_ds.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

            tab_friend.getColumnModel().getColumn(0).setPreferredWidth(30);
            tab_friend.getColumnModel().getColumn(1).setPreferredWidth(100);

            tab_group.getColumnModel().getColumn(0).setPreferredWidth(30);
            tab_group.getColumnModel().getColumn(1).setPreferredWidth(100);

            tab_friend_ds.getColumnModel().getColumn(0).setPreferredWidth(30);
            tab_friend_ds.getColumnModel().getColumn(1).setPreferredWidth(30);
            tab_friend_ds.getColumnModel().getColumn(2).setPreferredWidth(70);

            list_friend_controller = new List_friend_controller();
            friend_accept_controller = new Friend_accept_controller();
            friend_send_controller = new Friend_send_controller();
            other_user_controller = new Other_user_controller();
            chat_controller = new Chat_controller();
            insertmssql = new InsertMSSQL();
            data_user = new Data_User();
            group_list_controller = new Group_list_controller();
            group_controller = new Group_controller();

            ds_List_friend = new ArrayList<>();

            dtm = (DefaultTableModel) tab_friend_ds.getModel();
            dtm.setRowCount(0);

            ds_List_friend = new ArrayList();
            ResultSet rs_list_friend = list_friend_controller.SelectAll();

            while (rs_list_friend.next()) {
                List_friend_model dtMau = new List_friend_model(rs_list_friend.getString(2), rs_list_friend.getString(2));
                ds_List_friend.add(dtMau);
            }

            ds_Friend_accept = new ArrayList<>();
            ResultSet rs_friend_accept = friend_accept_controller.SelectAll();

            while (rs_friend_accept.next()) {
                Friend_accept_model dtMau = new Friend_accept_model(rs_friend_accept.getString(1));
                ds_Friend_accept.add(dtMau);
            }

            ds_Friend_send = new ArrayList<>();
            ResultSet rs_friend_send = friend_send_controller.SelectAll();

            while (rs_friend_send.next()) {
                Friend_send_model dtMau = new Friend_send_model(rs_friend_send.getString(1));
                ds_Friend_send.add(dtMau);
            }

            ds_Other_user = new ArrayList<>();
            ResultSet rs_other_user = other_user_controller.SelectAll();

            while (rs_other_user.next()) {
                Other_user_model dtMau = new Other_user_model(
                        rs_other_user.getString(1),
                        rs_other_user.getString(2),
                        rs_other_user.getString(3),
                        rs_other_user.getString(4),
                        rs_other_user.getString(5),
                        rs_other_user.getString(6),
                        rs_other_user.getString(7));
                ds_Other_user.add(dtMau);
            }

            ResultSet rs_All_Other_user = other_user_controller.SelectAll();
            dsGroup_list_paticipant = new ArrayList<>();

            while (rs_All_Other_user.next()) {
                ArrayList<Group_list_model> dsTemp = data_user.READ_TO_GROUP_CHAT(rs_All_Other_user.getString(1), loginname);

                for (Group_list_model item : dsTemp) {

                    Integer ID_group = item.getID_group();

                    String Username_Other_user = item.getUsername_other_user().substring(item.getUsername_other_user().indexOf("=") + 1, item.getUsername_other_user().length());

                    Group_list_model dtmau = new Group_list_model(ID_group, Username_Other_user);

                    dsGroup_list_paticipant.add(dtmau);
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    ArrayList<Group_list_model> dsGroup_list_paticipant;
    int luaChonTab = 0;

    private void ShowDown() {
        try {
            dtm = (DefaultTableModel) tab_friend.getModel();
            dtm.setRowCount(0);
            ds_List_friend.forEach(item
                    -> {

                ds_Other_user.forEach(item2
                        -> {
                    if (item2.getUsername_other_user().equals(item.getUsername_other_user()) && !item2.getUsername_other_user().equals("system")) {
                        dtm.addRow(new Object[]{item2.getImage_avatar(), item.getUsername_user()});
                    }
                }
                );
            }
            );
            dtm = (DefaultTableModel) tab_friend_ds.getModel();
            dtm.setRowCount(0);

            if (luaChonTab == 0) {
                ds_Friend_accept.forEach(item
                        -> {

                    ds_Other_user.forEach(item2
                            -> {
                        if (item2.getUsername_other_user().equals(item.getUsername_other_user())) {
                            dtm.addRow(new Object[]{item2.getImage_avatar(), item2.getUsername_other_user(), "Đang chờ", new JButton("Xóa")});
                        }
                    }
                    );
                }
                );
            } else {
                ds_Friend_send.forEach(item
                        -> {

                    ds_Other_user.forEach(item2
                            -> {
                        if (item2.getUsername_other_user().equals(item.getUsername_other_user())) {
                            dtm.addRow(new Object[]{item2.getImage_avatar(), item2.getUsername_other_user(), "Kết bạn", new JButton("Xóa")});
                        }
                    }
                    );
                }
                );
            }

            dtm = (DefaultTableModel) tab_group.getModel();
            dtm.setRowCount(0);

            // ID_group=1; Username_other_user=haiyen
            ResultSet rs = group_list_controller.SelectAll();

            while (rs.next()) {
                Group_model dtMau = group_controller.Select(rs.getInt(1) + "");
                dtm.addRow(new Object[]{dtMau.getImage_group(), dtMau.getName_group()});
            }

            tab_friend_ds.getColumnModel().getColumn(0).setCellRenderer(new ListFriend_view.ImageRender());
            tab_friend.getColumnModel().getColumn(0).setCellRenderer(new ListFriend_view.ImageRender());
            tab_group.getColumnModel().getColumn(0).setCellRenderer(new ListFriend_view.ImageRender());
            tab_friend_ds.setRowHeight(50);
            tab_friend.setRowHeight(50);
            tab_group.setRowHeight(50);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    int luachon = 0;
    String Who_give_u;
    Group_list_controller group_list_controller;
    Group_controller group_controller;

    private void Accept() {
        luachon = tab_friend_ds.getSelectedRow();
        Who_give_u = (String) tab_friend_ds.getValueAt(luachon, 1);
        data_user = new Data_User();
        // Insert List_Friend vao DB Chat
        List_friend_model dtMau = new List_friend_model(loginname, Who_give_u);
        list_friend_controller.Insert(dtMau);
        String sql3 = "Delete From [Other_chat]";
        jdbc.Helper_JDBC.update(sql3, new ArrayList<>());

        // B1: Delete DB Send
        insertmssql = new InsertMSSQL();
        insertmssql.DELETE_SEND_TEMP();
        insertmssql.DELETE_LIST_FRIEND_TEMP();

        // B2: Ghi file Send vao DB
        insertmssql.INSERT_SEND_TEMP_TO_DB(Who_give_u);

        // B3: Delete Friend_accept va Send
        friend_accept_controller.Delete(Who_give_u);

        String sql = "DELETE FROM [Send_temp] Where Username_other_user = ?";
        ArrayList dsProp = new ArrayList();
        dsProp.add(loginname);
        jdbc.Helper_JDBC.update(sql, dsProp);

        sql = "INSERT INTO List_friend_temp VALUES (?,?)";
        dsProp = new ArrayList();
        dsProp.add(Who_give_u);
        dsProp.add(loginname);
        jdbc.Helper_JDBC.update(sql, dsProp);
        //B4.5: Xóa FileText Cũ 
        try {
            FileWriter folder_friend_send = new FileWriter("src//data_Mess_Zola//" + Who_give_u + "//Friend_send.txt");
            BufferedWriter BW = new BufferedWriter(folder_friend_send);
            BW.write("");

        } catch (Exception e) {
            e.printStackTrace();
        }
        // B5: Ghi DB moi vao file text
        data_user.WRITE_TO_LIST_FRIEND_TEMP(Who_give_u);
        data_user.WRITE_TO_SEND(Who_give_u);

        // B6: Insert New Text
        insertmssql.INSERT_OTHER_CHAT_TEXT_TO_DB(Who_give_u);
        String sql1 = "INSERT INTO Other_chat (Username_user, Username_other_user, ID_type, [Text], Who_send ) VALUES (?,?,?,?,?)";
        ArrayList dsProp1 = new ArrayList();
        dsProp1.add(Who_give_u);
        dsProp1.add(loginname);
        dsProp1.add(1);
        dsProp1.add("Xin Chào Bạn Nha, Mình Vừa Kết Bạn.");
        dsProp1.add(loginname);
        jdbc.Helper_JDBC.updateNvarchar(sql1, dsProp1);
        data_user.WRITE_TO_OTHER_CHAT(Who_give_u);

        Chat_model dtMau1 = new Chat_model(
                loginname,
                Who_give_u,
                1,
                "Xin Chào Bạn Nha, Mình Vừa Kết Bạn.",
                loginname);
        chat_controller.Insert(dtMau1);
        luachon = 0;
        // B7: Fill Lại từ đầu
        FillToTable();
        ShowDown();
//        Menu_view dtSetUpMenu_view = new Menu_view(loginname, 0);
        JOptionPane.showMessageDialog(this, "Kết bạn thành công rực rỡ!!");
    }

    private void Delete() {
        luachon = tab_friend_ds.getSelectedRow();
        Who_give_u = (String) tab_friend_ds.getValueAt(luachon, 1);

        // B1: Xóa hết dữ liệu trong DB, để chừa chỗ cho DB mới
        String sql3 = "Delete From [Other_chat]";
        jdbc.Helper_JDBC.update(sql3, new ArrayList<>());

        // B2: Load DB mới vào chỗ trống đã bày sẵn
        insertmssql.INSERT_SEND_TEMP_TO_DB(Who_give_u);

        // Xóa ở Loginame và cập nhật ở Who_give_u
        friend_accept_controller.Delete(Who_give_u);

        String sql = "DELETE FROM SEND_Temp WHERE Username_other_user = ?";
        ArrayList dsProp = new ArrayList();
        dsProp.add(loginname);
        jdbc.Helper_JDBC.update(sql, dsProp);

        // Ghi lại sự thay đổi vào trong file text 
        data_user.WRITE_TO_SEND(Who_give_u);

        // Tải dữ liệu mới từ DB lên
        FillToTable();
        ShowDown();
    }

    private void ShowInfo() {
        luachon = tab_friend_ds.getSelectedRow();
        Who_give_u = (String) tab_friend_ds.getValueAt(luachon, 1);

        Other_user_model dtMau = other_user_controller.Select(Who_give_u);
        Infomation_view dt = new Infomation_view(null, true, dtMau, 2, this);
        dt.setLocationRelativeTo(null);
        dt.setVisible(true);
    }

    private void ShowInfo2() {
        luachon2 = tab_friend.getSelectedRow();
        Who_give_u = (String) tab_friend.getValueAt(luachon2, 1);

        Other_user_model dtMau = other_user_controller.Select(Who_give_u);
        Infomation_view dt = new Infomation_view(null, true, dtMau, 2);
        dt.setLocationRelativeTo(null);
        dt.setVisible(true);
    }

    private void Delete_friend_Accept() {
        try {
            String Who_want_delete = (String) tab_friend.getValueAt(luachon2, 1);
            // B1: Xóa bảng List_friend_temp
            String sql = "DELETE FROM List_friend_temp";
            jdbc.Helper_JDBC.update(sql, new ArrayList<>());

            // B2: Insert DB vào trong bảng List_friend_temp
            insertmssql.INSERT_LIST_FRIEND_TEMP_TO_DB(Who_want_delete);

            // B3: Xóa kết bạn trong List_friend_temp ở phía Who_give_u
            String sql1 = "DELETE FROM List_friend_temp WHERE Username_other_user = ? ";
            ArrayList dsProp = new ArrayList();
            dsProp.add(loginname);
            jdbc.Helper_JDBC.update(sql1, dsProp);

            // B4: Xóa kết bạn trong List_friend
            list_friend_controller.Delete(Who_want_delete);

            // B6: Ghi lại sự thay đổi vào file text của Who_give_u
            data_user.WRITE_TO_LIST_FRIEND_TEMP(Who_want_delete);

            // B6: Load lại thay đổi.
            FillToTable();
            ShowDown();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void Delete_friend() {
        luachon = tab_friend_ds.getSelectedRow();
        Who_give_u = (String) tab_friend_ds.getValueAt(luachon, 1);

        // B1: Xóa hết dữ liệu trong DB, để chừa chỗ cho DB mới
        String sql3 = "Delete From [Other_chat]";
        jdbc.Helper_JDBC.update(sql3, new ArrayList<>());

        // B2: Load DB mới vào chỗ trống đã bày sẵn
        insertmssql.INSERT_ACCEPT_TEMP_TO_DB(Who_give_u);

        // Xóa ở Loginame và cập nhật ở Who_give_u
        friend_send_controller.Delete(Who_give_u);

        String sql = "DELETE FROM Accept_Temp WHERE Username_other_user = ?";
        ArrayList dsProp = new ArrayList();
        dsProp.add(loginname);
        jdbc.Helper_JDBC.update(sql, dsProp);

        // Ghi lại sự thay đổi vào trong file text 
        data_user.WRITE_TO_ACCEPT(Who_give_u);

        // Tải dữ liệu mới từ DB lên
        FillToTable();
        ShowDown();
    }

    private class ImageRender extends DefaultTableCellRenderer {

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value,
                boolean isSelected, boolean hasFocus, int row, int column) {
            String Photoname = "/image_user_avatar/" + value.toString();
            Icon imageIcon = new ImageIcon(new ImageIcon(Objects.requireNonNull(this.getClass().getResource(Photoname))).getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH));
            return new JLabel(imageIcon);
        }

    }

}
