/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.Capcha_controller;
import controller.User_controller;
import java.awt.Color;
import java.awt.Image;
import java.util.ArrayList;
import java.sql.*;
import java.util.Random;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.Capcha_model;
import model.User_model;

/**
 *
 * @author Huy1721
 */
public class Login_view extends javax.swing.JFrame {

    /**
     * Creates new form Login_view
     */
    public Login_view() {
        initComponents();
        LoadWho_login();
        setUp();
        getRootPane().setBorder(BorderFactory.createMatteBorder(4, 4, 4, 4, Color.GRAY));
        Random();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        input_login_tendangnhap = new javax.swing.JTextField();
        input_login_password = new javax.swing.JPasswordField();
        input_login_Capcha = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        rdo_login_rememberMe1 = new javax.swing.JCheckBox();
        jButton4 = new javax.swing.JButton();
        input_code_capcha = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Nirmala UI", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Zola");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        input_login_tendangnhap.setText("Tên đăng nhập");
        input_login_tendangnhap.setToolTipText("Tên đăng nhập");
        input_login_tendangnhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                input_login_tendangnhapMouseClicked(evt);
            }
        });

        input_login_password.setText("MatKhau");
        input_login_password.setToolTipText("Mật khẩu");
        input_login_password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                input_login_passwordMouseClicked(evt);
            }
        });

        input_login_Capcha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton1.setText("Tải hình mới");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        rdo_login_rememberMe1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdo_login_rememberMe1.setText("Nhớ tài khoản");
        rdo_login_rememberMe1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_login_rememberMe1ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(51, 51, 255));
        jButton4.setText("Hiện");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        input_code_capcha.setText("Mã captcha");
        input_code_capcha.setToolTipText("Tên đăng nhập");
        input_code_capcha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                input_code_capchaMouseClicked(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(0, 0, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("tạo tài khoản ngay");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(rdo_login_rememberMe1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(input_login_password, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)
                            .addComponent(input_code_capcha, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(input_login_Capcha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)))
                    .addComponent(input_login_tendangnhap))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(input_login_tendangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(input_login_password)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_code_capcha, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(input_login_Capcha, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdo_login_rememberMe1)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Đăng nhập", jPanel2);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Đăng nhập tài khoản");

        jButton2.setBackground(new java.awt.Color(0, 0, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Đăng nhập");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton3.setBackground(new java.awt.Color(204, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("X");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jLabel1))
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            User_controller user_controller = new User_controller();
            String sql = "SELECT * FROM Exit_or_not";
            ResultSet rs = jdbc.Helper_JDBC.query(sql, new ArrayList());

            if (checkEmpty() && checkOtherUser() && rs.next() && trueCapcha()) { // 
                user_controller.Insert(new User_model(input_login_tendangnhap.getText(), input_login_password.getText()));
                Menu_view dt = new Menu_view(input_login_tendangnhap.getText(), rs.getInt(1));
                dt.setVisible(true);
                setVisible(false);
                // ghi lại tên để nhớ người dùng
                if (signal == 1) {
                    String sql1 = "UPDATE Who_login set Username_other_user = ?";
                    ArrayList dsProp = new ArrayList<>();
                    dsProp.add(input_login_tendangnhap.getText());
                    jdbc.Helper_JDBC.update(sql1, dsProp);
                } else {
                    String sql1 = "UPDATE Who_login set Username_other_user = ?";
                    ArrayList dsProp = new ArrayList<>();
                    dsProp.add("");
                    jdbc.Helper_JDBC.update(sql1, dsProp);
                }

            } else {
                JOptionPane.showMessageDialog(rootPane, "Sai thông tin đăng nhập");
                this.jButton1ActionPerformed(evt);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    int signal = 0;

    private void rdo_login_rememberMe1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_login_rememberMe1ActionPerformed
        if (rdo_login_rememberMe1.isSelected()) {
            signal = 1;
        } else {
            signal = 0;
        }
    }//GEN-LAST:event_rdo_login_rememberMe1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Thoát chương trình thành công!! ");
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void input_login_tendangnhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_input_login_tendangnhapMouseClicked
        if (input_login_tendangnhap.getText().equals("Tên đăng nhập")) {
            input_login_tendangnhap.setText("");
        }
    }//GEN-LAST:event_input_login_tendangnhapMouseClicked

    private void input_login_passwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_input_login_passwordMouseClicked
        if (input_login_password.getText().equalsIgnoreCase("matkhau")) {
            input_login_password.setText("");
        }
    }//GEN-LAST:event_input_login_passwordMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        if (show_hide_int == 0) {
            input_login_password.setEchoChar((char) 0);
            jButton4.setText("Ẩn");
            show_hide_int = 1;
        } else {
            input_login_password.setEchoChar('*');
            jButton4.setText("Hiện");
            show_hide_int = 0;
        }

    }//GEN-LAST:event_jButton4ActionPerformed


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Random();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void input_code_capchaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_input_code_capchaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_input_code_capchaMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        Register_view dtMau = new Register_view();
        dtMau.setLocationRelativeTo(null);
        dtMau.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel5MouseClicked

    int show_hide_int = 0;
    static User_controller user_controller;

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    String sql = "SELECT * FROM Exit_or_not";
                    ResultSet rs = jdbc.Helper_JDBC.query(sql, new ArrayList());
                    if (rs.next()) {
                        if (rs.getInt(1) == 1) {
                            Login_view dtMau = new Login_view();
                            dtMau.setVisible(true);
                        } else if (rs.getInt(1) == 0) {
                            user_controller = new User_controller();
                            ResultSet rsv = user_controller.SelectAll();
                            if (rsv.next()) {
                                Menu_view dt = new Menu_view(rsv.getString(1), rs.getInt(1));
                                dt.setVisible(true);
                            }
                        }
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField input_code_capcha;
    private javax.swing.JLabel input_login_Capcha;
    private javax.swing.JPasswordField input_login_password;
    private javax.swing.JTextField input_login_tendangnhap;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JCheckBox rdo_login_rememberMe1;
    // End of variables declaration//GEN-END:variables

    ArrayList<Capcha_model> dsImage;
    ResultSet rs_Capcha;
    Capcha_controller capcha_controller;

    private void setUp() {
        try {
            setLocationRelativeTo(null);
            setResizable(false);
            setTitle("Zola");
            capcha_controller = new Capcha_controller();
            dsImage = new ArrayList();
            rs_Capcha = capcha_controller.SelectAll();

            while (rs_Capcha.next()) {
                Capcha_model dtMau = new Capcha_model(rs_Capcha.getString(1), rs_Capcha.getString(2), rs_Capcha.getString(3));
                dsImage.add(dtMau);
            }
//        setUndecorated(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    int n = 0;

    public void Random() {

        Random rand = new Random();
        n = rand.nextInt(4);
        ImageIcon image = new ImageIcon(getClass().getResource("/image_Capcha/" + dsImage.get(n).getImage_capcha()));
        
        Image img = image.getImage();

        image = new ImageIcon(img);
        input_login_Capcha.setIcon(image);
        input_code_capcha.setText("");

    }

    private boolean checkEmpty() {
        if (!input_login_tendangnhap.getText().equals("") && !input_login_password.getText().equals("") && !input_code_capcha.getText().equals("")) {
            return true;
        }
        return false;
    }

    private boolean checkOtherUser() {
        try {
            String sql = "SELECT Username_other_user, Password FROM Other_user";
            ResultSet rs = jdbc.Helper_JDBC.queryNvarchar(sql, new ArrayList());

            while (rs.next()) {
                if (rs.getString(1).equals(input_login_tendangnhap.getText()) && rs.getString(2).equals(input_login_password.getText())) {
                    return true;
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return false;
    }

    private boolean trueCapcha() {
        if ((input_code_capcha.getText() + " ").equals(dsImage.get(n).getCode_capcha())) {
            return true;
        }

        return false;
    }

    private void LoadWho_login() {
        try {
            String sql = "SELECT * FROM Who_login";
            ArrayList dsProp = new ArrayList();
            ResultSet rs = jdbc.Helper_JDBC.query(sql, dsProp);
            if (rs.next()) {
                if (!rs.getString(1).equals("")) {
                    input_login_tendangnhap.setText(rs.getString(1));
                } else {
                    input_login_tendangnhap.setText("Tên đăng nhập");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

}
