/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.Friend_accept_controller;
import controller.Friend_send_controller;
import controller.Other_user_controller;
import java.awt.Component;
import java.awt.Image;
import java.sql.*;
import java.util.ArrayList;
import java.util.Objects;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import jdbc.Data_User;
import jdbc.InsertMSSQL;
import model.Friend_send_model;
import model.MessViewTemp;
import model.Other_user_model;

/**
 *
 * @author Huy1721
 */
public class Seach_view extends javax.swing.JDialog {

    /**
     * Creates new form Seach_view
     */
    InsertMSSQL insertMSSQL;
    String loginname;
    Friend_send_controller friend_send_controller;
    Data_User data_user;
    Messenger_view panel;

    public Seach_view(java.awt.Frame parent, boolean modal, String loginname, Messenger_view jpannel) {
        super(parent, modal);
        initComponents();
        panel = jpannel;
        this.loginname = loginname;
        FillToTable();
        ShowDown();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabBang = new javax.swing.JTable();
        input_Seach_Username = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tabBang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabBang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabBangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabBang);

        input_Seach_Username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                input_Seach_UsernameMousePressed(evt);
            }
        });
        input_Seach_Username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                input_Seach_UsernameKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Tìm kiếm bạn bè");

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Kết bạn ngay!!!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(input_Seach_Username, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(input_Seach_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void input_Seach_UsernameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_input_Seach_UsernameMousePressed
        input_Seach_Username.setText("");
    }//GEN-LAST:event_input_Seach_UsernameMousePressed

    private void input_Seach_UsernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_input_Seach_UsernameKeyPressed
        FillToTable();
        ShowDown();
    }//GEN-LAST:event_input_Seach_UsernameKeyPressed

    int luachon = 0;

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String Who_give_u = (String) tabBang.getValueAt(luachon, 1);
        
        // B1: Xóa Accept_temp để chừa chỗ trống lát điền data vào
        insertMSSQL.DELETE_ACCEPT_TEMP();

        // B2: Ghi dữ liệu từ file text vào Accept_temp
        insertMSSQL.INSERT_ACCEPT_TEMP_TO_DB(Who_give_u);

        // B3: Thêm lời kết bạn vào Friend_send của loginname
        Friend_send_model dtMau = new Friend_send_model(Who_give_u);
        friend_send_controller.Insert(dtMau);

        // B4: Thêm lời kết bạn vào Accept_temp của Who_give_u
        String sql = "INSERT INTO Accept_temp VALUES (?)";
        ArrayList dsProp = new ArrayList();
        dsProp.add(loginname);
        jdbc.Helper_JDBC.update(sql, dsProp);

        // B5: Ghi DB vào file text của Who_give_u
        data_user.WRITE_TO_ACCEPT(Who_give_u);
        FillToTable();
        ShowDown();
        
        // B6 Thông báo và load lại dữ liệu
        JOptionPane.showMessageDialog(rootPane, "Đã gửi lời mời kết bạn đến " + Who_give_u);
        panel.FillToTable();
        panel.ShowDown();
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tabBangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabBangMouseClicked
        luachon = tabBang.getSelectedRow();
    }//GEN-LAST:event_tabBangMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField input_Seach_Username;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabBang;
    // End of variables declaration//GEN-END:variables

    Other_user_controller other_user_controller;
    String ma;
    ArrayList<MessViewTemp> ds_Other_user;
    DefaultTableModel dtm;

    private void FillToTable() {
        try {
            tabBang.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            
            insertMSSQL = new InsertMSSQL();
            tabBang.getColumnModel().getColumn(0).setMaxWidth(70);
            data_user = new Data_User();

            ma = input_Seach_Username.getText();
            ds_Other_user = new ArrayList<>();
            friend_send_controller = new Friend_send_controller();
            other_user_controller = new Other_user_controller();
            String sql = "SELECT O_u.Username_other_user, Image_avatar FROM Other_user O_u WHERE O_u.Username_other_user like ? and O_u.Username_other_user not in (SELECT Username_other_user FROM List_friend) and O_u.Username_other_user not in (?, ?) and O_u.Username_other_user not in (SELECT * FROM Friend_send) and O_u.Username_other_user not in (SELECT * FROM Friend_accept)";
            ArrayList dsProp = new ArrayList();
            dsProp.add("%" + ma + "%");
            dsProp.add(loginname);
            dsProp.add("system");
            ResultSet rs = jdbc.Helper_JDBC.query(sql, dsProp);
            while (rs.next()) {
                if (rs.getString(1).equals("system")) {
                    continue;
                }
                MessViewTemp dtMau = new MessViewTemp(
                        rs.getString(2),
                        rs.getString(1)
                );
                ds_Other_user.add(dtMau);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void ShowDown() {
        dtm = (DefaultTableModel) tabBang.getModel();
        dtm.setRowCount(0);

        for (MessViewTemp item : ds_Other_user) {
            dtm.addRow(new Object[]{item.getImage_avatar(), item.getUsername_other_user()});
        }

        tabBang.getColumnModel().getColumn(0).setCellRenderer(new Seach_view.ImageRender());
        tabBang.setRowHeight(50);
    }

    private class ImageRender extends DefaultTableCellRenderer {

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value,
                boolean isSelected, boolean hasFocus, int row, int column) {
            String Photoname = "/image_user_avatar/" + value.toString();
            Icon imageIcon = new ImageIcon(new ImageIcon(Objects.requireNonNull(this.getClass().getResource(Photoname))).getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH));
            return new JLabel(imageIcon);
        }
    }

}
