/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.Friend_accept_controller;
import controller.Friend_send_controller;
import controller.Group_chat_controller;
import controller.Group_controller;
import controller.Group_list_controller;
import controller.Other_user_controller;
import java.awt.Component;
import java.awt.Image;
import java.sql.*;
import java.util.ArrayList;
import java.util.Objects;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import jdbc.Data_User;
import jdbc.InsertMSSQL;
import model.Friend_send_model;
import model.Group_chat_model;
import model.Group_list_model;
import model.Group_model;
import model.MessViewTemp;
import model.Other_user_model;

/**
 *
 * @author Huy1721
 */
public class Seach_group_view extends javax.swing.JDialog {

    /**
     * Creates new form Seach_view
     */
    InsertMSSQL insertMSSQL;
    String loginname;
    Friend_send_controller friend_send_controller;
    Data_User data_user;
    Messenger_view panel;

    Group_controller group_controller;
    Group_list_controller group_list_controller;
    Group_chat_controller group_chat_controller;

    public Seach_group_view(java.awt.Frame parent, boolean modal, String loginname, Messenger_view jpannel) {
        super(parent, modal);
        initComponents();
        panel = jpannel;
        this.loginname = loginname;
        FillToTable();
        ShowDown();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabBanggroup = new javax.swing.JTable();
        input_Seach_Group = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnJoinGroup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tabBanggroup.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabBanggroup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabBanggroupMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabBanggroup);

        input_Seach_Group.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                input_Seach_GroupMousePressed(evt);
            }
        });
        input_Seach_Group.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                input_Seach_GroupKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Tìm Kiếm Nhóm");

        btnJoinGroup.setBackground(new java.awt.Color(51, 51, 255));
        btnJoinGroup.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnJoinGroup.setForeground(new java.awt.Color(255, 255, 255));
        btnJoinGroup.setText("Join nhóm ngay!!!");
        btnJoinGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJoinGroupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnJoinGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(input_Seach_Group, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(input_Seach_Group, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnJoinGroup, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void input_Seach_GroupMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_input_Seach_GroupMousePressed
        input_Seach_Group.setText("");
    }//GEN-LAST:event_input_Seach_GroupMousePressed

    private void input_Seach_GroupKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_input_Seach_GroupKeyPressed
        FillToTable();
        ShowDown();
    }//GEN-LAST:event_input_Seach_GroupKeyPressed

    int luachon = 0;

    private void btnJoinGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJoinGroupActionPerformed
        try {
            group_chat_controller = new Group_chat_controller();
            String tenNhom = (String) tabBanggroup.getValueAt(luachon, 1);
            String sql = "Select ID_group FROM [Group] WHERE Name_group = ?";
            ArrayList dsProp = new ArrayList();
            dsProp.add(tenNhom);
            ResultSet rs = jdbc.Helper_JDBC.query(sql, dsProp);

            // Insert vao DB 
            if (rs.next()) {
                Group_list_model dtMau = new Group_list_model(rs.getInt(1), loginname);
                group_list_controller.Insert(dtMau);
//
//                Group_chat_model dtMauGroupChat = new Group_chat_model(1, rs.getInt(1), loginname, 1, loginname + " vừa gia nhập nhóm.");
//                group_chat_controller.Insert(dtMauGroupChat);
//
//                // Insert vào DB Group_chat_inventory
//                String sql1 = "INSERT INTO Group_chat_inventory VALUES (?,?,?,?)";
//                ArrayList dsProp1 = new ArrayList<>();
//                dsProp1.add(rs.getInt(1));
//                dsProp1.add(loginname);
//                dsProp1.add(1);
//                dsProp1.add(loginname + " vừa gia nhập nhóm.");
//                jdbc.Helper_JDBC.update(sql1, dsProp1);

                // WRITE TO GROUP_CHAT
                //
                try {
                    // step 1: lấy dữ liệu danh sách tất cả người giam gia
                    ResultSet rs_All_Other_user = other_user_controller.SelectAll();
                    ArrayList<Group_list_model> dsGroup_list_paticipant = new ArrayList<>();

                    while (rs_All_Other_user.next()) {
                        ArrayList<Group_list_model> dsTemp = data_user.READ_TO_GROUP_CHAT(rs_All_Other_user.getString(1), loginname);

                        for (Group_list_model item : dsTemp) {
                            dsGroup_list_paticipant.add(item);
                        }

                        data_user.CLEAN_TO_GROUP_CHAT(rs_All_Other_user.getString(1), loginname);
                    }

                    // step 2: thêm dữ liệu vào bảng Group_chat_inv
                    
                    String tenNhom1 = (String) tabBanggroup.getValueAt(tabBanggroup.getSelectedRow(), 1);

                    
                    
                    StringBuilder stringBuilder = new StringBuilder(tenNhom1);
                    stringBuilder.deleteCharAt(0);

                    String sql2 = "SELECT ID_group FROM [Group] WHERE Name_group = ?";
                    ArrayList dsPropList = new ArrayList<>();
                    dsPropList.add(tenNhom1);
                    ResultSet rs2 = jdbc.Helper_JDBC.query(sql2, dsPropList);

                    if (rs2.next()) {
                        String sql3 = "INSERT INTO Group_chat_inventory VALUES (?,?,?,?)";
                        ArrayList dsProp2 = new ArrayList();
                        dsProp2.add(rs2.getInt(1));
                        dsProp2.add(loginname);
                        dsProp2.add(1);
                        dsProp2.add(loginname + " vừa gia nhập nhóm.");
                        jdbc.Helper_JDBC.update(sql3, dsProp2);
                        // step 3: thêm tin nhắn nhóm vào Group_chat
                        Group_chat_model dtMauk = new Group_chat_model(1, rs2.getInt(1), loginname, 1, loginname + " vừa gia nhập nhóm.");
                        group_chat_controller.Insert(dtMauk);
                    }

                    // step 5: thêm dữ liệu vào từng file text Group_chat
                    for (Group_list_model item : dsGroup_list_paticipant) {
                        data_user.WRITE_TO_GROUP_CHAT(item, loginname);
                    }

                } catch (Exception e) {
                    e.printStackTrace();
                }
                
                FillToTable();
                ShowDown();

                // B6 Thông báo và load lại dữ liệu
                JOptionPane.showMessageDialog(rootPane, "Đã tham gia thành công nhóm " + tenNhom);
                panel.FillToTable();
                panel.ShowDown();
                panel.get_evt_tab_mess_group_showMouseClicked();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnJoinGroupActionPerformed

    private void tabBanggroupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabBanggroupMouseClicked
        luachon = tabBanggroup.getSelectedRow();
    }//GEN-LAST:event_tabBanggroupMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJoinGroup;
    private javax.swing.JTextField input_Seach_Group;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabBanggroup;
    // End of variables declaration//GEN-END:variables

    Other_user_controller other_user_controller;
    String ma;
    ArrayList<Group_list_model> ds_groupList;
    DefaultTableModel dtm;

    private void FillToTable() {
        try {
            group_controller = new Group_controller();
            group_list_controller = new Group_list_controller();
            tabBanggroup.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

            insertMSSQL = new InsertMSSQL();
            tabBanggroup.getColumnModel().getColumn(0).setMaxWidth(70);
            data_user = new Data_User();

            ma = input_Seach_Group.getText();

            ds_groupList = new ArrayList<>();

            friend_send_controller = new Friend_send_controller();
            other_user_controller = new Other_user_controller();
            String sql = "SELECT DISTINCT  G.ID_group ,G.Name_group FROM [Group] G WHERE G.ID_group not in (SELECT ID_group FROM Group_list) and G.Name_group like ?";
            ArrayList dsProp = new ArrayList();
            dsProp.add("%" + ma + "%");
            ResultSet rs = jdbc.Helper_JDBC.query(sql, dsProp);
            while (rs.next()) {
                int number = rs.getInt(1);
                String NameGroup = rs.getString(2);

                Group_list_model dtMau = new Group_list_model(
                        number, NameGroup);

                ds_groupList.add(dtMau);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void ShowDown() {
        dtm = (DefaultTableModel) tabBanggroup.getModel();
        dtm.setRowCount(0);

        for (Group_list_model item : ds_groupList) {
            Group_model dtMau = group_controller.Select(item.getID_group() + "");
            dtm.addRow(new Object[]{dtMau.getImage_group(), item.getUsername_other_user()});
        }

        tabBanggroup.getColumnModel().getColumn(0).setCellRenderer(new Seach_group_view.ImageRender());
        tabBanggroup.setRowHeight(50);
    }

    private class ImageRender extends DefaultTableCellRenderer {

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value,
                boolean isSelected, boolean hasFocus, int row, int column) {
            String Photoname = "/image_user_avatar/" + value.toString();
            Icon imageIcon = new ImageIcon(new ImageIcon(Objects.requireNonNull(this.getClass().getResource(Photoname))).getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH));
            return new JLabel(imageIcon);
        }
    }

}
